# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "persistent-chat"
mod.group = "dev.liqw"
mod.version = "2.0.1"
description = "Keep your chat history between game sessions"
sources_url = "https://github.com/liqwtf/persistent-chat"
issues_url = "https://github.com/liqwtf/persistent-chat/issues"

loomx.loom_version = "1.16-SNAPSHOT"
loader_version = "0.19.1"

publish.modrinth = "kzOJywOa"
publish.curseforge = "1509355"

["26.1"]
minecraft_version = "~26.1"
publish_versions = ["26.1", "26.1.1", "26.1.2"]
fabric_api_version = "0.145.1+26.1"
cloth_config_version = "26.1.154"
mod_menu_version = "18.0.0-alpha.8"

["1.21.11"]
minecraft_version = "~1.21.11"
publish_versions = ["1.21.11"]
fabric_api_version = "0.141.3+1.21.11"
cloth_config_version = "21.11.153"
mod_menu_version = "17.0.0"

["1.21.1"]
minecraft_version = "~1.21.1"
publish_versions = ["1.21.1"]
fabric_api_version = "0.116.11+1.21.1"
cloth_config_version = "15.0.140"
mod_menu_version = "11.0.4"